services:
  postgres:
    image: postgres:15
    container_name: cicd_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cicd_learn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cicd_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cicd_redis
    ports:
      - "6379:6379"
    networks:
      - cicd_network
    restart: unless-stopped

  app:
    image: ${DOCKERHUB_USERNAME}/learncicd:latest
    container_name: cicd_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - cicd_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cicd_network:
    driver: bridge