name: Deploy API

on:
  push:
    branches: [ "main" ]   # запуск при пуше в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ставим Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Логинимся в Docker Hub (чтобы пушить образ)
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Собираем и пушим образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-api:latest

      # 5. Деплой на сервер через SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-api:latest
            docker stop my-api || true
            docker rm my-api || true
            docker run -d -p 8080:8080 --name my-api ${{ secrets.DOCKERHUB_USERNAME }}/my-api:latest
